"""second migration

Revision ID: 1eed1dd4d75d
Revises: da446eb19d65
Create Date: 2023-12-02 04:01:21.532030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eed1dd4d75d'
down_revision = 'da446eb19d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_sid', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_column('recipient_sid')

    # ### end Alembic commands ###
